plugins {
    id "fabric-loom" version "1.10-SNAPSHOT" apply false
    id "com.gradleup.shadow" version "9.0.0-beta4" apply false
}
dependencyLocking {
    lockAllConfigurations()
}

allprojects {
    group = project.maven_group
    version = project.mod_version

    repositories {
        mavenCentral()
        maven { url = "https://maven.fabricmc.net/" }

        maven {
            url = "https://maven.dediamondpro.dev/releases/"
            name = "DeDiamondPro"
            content {

                includeGroup "dev.dediamondpro"
            }
        }
        maven {
            url = uri('https://mcef-download.cinemamod.com/repositories/releases')
            name = "CinemaMod"
            content {

                excludeGroup "dev.dediamondpro"
            }
        }
    }
}