modLoader = "javafml"
loaderVersion = "*"
license = "LGPLv3"
issueTrackerURL="https://github.com/RedxAx/Remotely/issues"

[[mods]]
modId = "remotely"
version = "${version}"
displayName = "${name}"
authors = "RedxAx, DumpFridge"
description = ""
logoFile = "assets/remotely/Reemotely.png"
logoBlur = false

[[mixins]]
config = "remotely-common.mixins.json"