modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
    modId = "remotely"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = '''${mod_description}'''
    authors = "${mod_author}"

[[remotely]]
    modId = "neoforge"
    mandatory = true
    ordering = "NONE"
    side = "BOTH"

[[remotely]]
    modId = "minecraft"
    mandatory = true