blank_issues_enabled: true
contact_links:
  - name: For help with other issues, join our Discord community
    url: https://dsc.gg/RedxAxStudios
    about: This is the best option for getting help with mod installation, performance issues, and any other support inquiries.
