mod.name=Remotely
mod.id=remotely
mod.group=redxax.oxy.remotely

dgt.loom.mappings=official-like
dgt.minecraft.revision=3

org.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.workers.max=3
org.gradle.configureondemand=true

loom.ignoreDependencyLoomVersionValidation=true
