mod.name=Remotely
mod.id=remotely
mod.group=redxax.oxy.remotely
remotely.publish.changelog=### Remotely Changes:\n\
- Feat: Node Families Exposes Modes In Node Search.\n\
- Fix: Various Stuff.\n\
- Feat: Flow Editor UI/UX Improvements.\n\
- Feat: Custom Plan Configuration.\n\
- Fix: ESC Key Handling.\n\
- Feat: ReProxy.\n\
- Feat(RemotelyMod): Floating Windows, Some Fixes.\n\
- Fix: Rewrite Gradle Structure Again.\n\
### Rebase Changes:\n\
- Fix: ESC Key Handling.\n\
- Feat: ReProxy.\n\
- Feat(RemotelyMod): Floating Windows, Some Fixes.\n\
- Feat: Disable Animations Option.\n\
- Feat(Relaunched): Import-Launcher, Java JRE Polishments, And More.\n\
- Fix: Relaunched Minecraft Account Persistence.\n\
### ReScreen Changes:\n\
- Feat(RemotelyMod): Floating Windows, Some Fixes.\n\
- Feat: Disable Animations Option.\n\
- Fix: Edge-Cases Where Desktop Animations Break.

dgt.loom.mappings=official-like
dgt.minecraft.revision=3

org.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8
org.gradle.configureondemand=true

loom.ignoreDependencyLoomVersionValidation=true
