name: Default
colors:
  globalDarkTextColor: "#FF888888"
  terminalTextWarnColor: "#FFFFA500"
  buttonTextBrowseColor: "#FF249FDE"
  globalCursorColor: "#FFD6F264"
  terminalTextErrorColor: "#FFFF0000"
  elementBorderColor: "#FF444444"
  buttonTextStopColor: "#FFFF7A7A"
  globalTextColor: "#FFFFFFFF"
  HangarBackgroundColor: "#FF17253B"
  ModrinthBorderColor: "#FFD6F264"
  terminalStatusBarColor: "#FF555555"
  browserElementTextDimColor: "#FFD6F264"
  buttonTextStartColor: "#FFD6F264"
  calmAccentColor: "#FF6CC4F1"
  dangerLightAccentColor: "#FFFF7A7A"
  innerBackgroundSelectedColor: "#FF526644"
  accentDarkColor: "#FF0B371C"
  innerBorderColor: "#FF333333"
  innerBackgroundColor: "#FF222222"
  niceAccentColor: "#FFFFC800"
  elementHoverBorderColor: "#FF9D9D9D"
  SpigotBorderColor: "#FFFFC800"
  HangarBorderColor: "#FF6CC4F1"
  globalOuterBorder: "#FF000000"
  searchBarBorderColor: "#FF444444"
  terminalTextInfoColor: "#FF00FF00"
  searchBarBackgroundColor: "#FF2C2C2C"
  buttonTextExplorerHoverColor: "#FFFFC800"
  terminalCursorColor: "#FFFFFFFF"
  buttonTextExplorerColor: "#FFBFAB61"
  backgroundColor: "#FF181818"
  ModrinthBackgroundColor: "#FF0B371C"
  terminalTextInputColor: "#FFD6F264"
  accentColor: "#FFD6F264"
  elementBackgroundColor: "#FF2C2C2C"
  calmDarkAccentColor: "#FF17253B"
  dangerDarkAccentColor: "#FFDF3E23"
  dangerAccentColor: "#FF3B1725"
  globalSelectionColor: "#80FFFFFF"
  buttonTextBrowseHoverColor: "#FF6CC4F1"
  elementHoverBackgroundColor: "#FF444444"
  globalHoverTextColor: "#FFD6F264"
  SpigotBackgroundColor: "#FF3B2D17"
  terminalTextColor: "#FFFFFFFF"
  niceDarkAccentColor: "#FF3B1725"
  terminalBackgroundColor: "#FF181818"
